#!/bin/bash
# Palette installer votre distrib xBuntu grâce à un Buntufile ! 

#Chargement des bibliothèques
charge_libs() {
  libs="log std"
  for lib in $libs; do
    . ${SFLIB}/${lib}.lib || erreur "Chargmenent de la bibliothèque [$lib] : impossible "
    sflib_log_debug "Chargmenent de la bibliothèque [$lib] : OK"
    sflib_${lib}_init || "Initialisation de la bibliothèque [$lib] : impossible "
    sflib_log_debug "Initialisation de la bibliothèque [$lib] : OK"
  done
}

init() {
  check_sf
  charge_libs
  buntufile=Buntufile
  sflib_std_fic_test $buntufile
}

sortie() {
  rc=$1
  [ $SEVERITE -ne 0 ] && rc=$SEVERITE
  [ $rc -eq 0 ] && trace "Palette install completed." || erreur "Palette install error [$rc]"
  exit $rc
}

check_sf() {
  [ -z "$SFLIB" ] && echo " ! ShellFactory n'est pas installé ! 
  https://github.com/cchaudier/shellfactory" && exit 1
}

test_os() {
  trace "Test OS version"
  grep "$os_version" /etc/issue >/dev/null|| (trace "OS not $os_version" && sortie 1)
  trace " --> Os OK"
}

update() {
  trace "Update packages list"
  sudo dpkg --configure -a >/dev/null
  sudo apt-get update -y >/dev/null
}

upgrade() {
  trace "Upgrade packages"
  sudo apt-get upgrade -y  >/dev/null
}

install_deb() {
  trace " --> Install packet apt $packet"
  [ -n "$version" ] && opt_version="=$version"
  sudo apt-get install -y $packet$opt_version >/dev/null
  sflib_std_test_returncode "    Installation du packet impossible !"
}

install_line() {
  mot_clef=$(echo $line|cut -f 1 -d ' ')
  case $mot_clef in
    source|deb) 
    trt_$mot_clef $line;;
    '');;
    *) warning "Mot clef [$mot_clef] inconnu !"
  esac
}

trt_source() {
  key=$(echo $line|cut -f 2 -d "'")
  repo=$(echo $line|cut -f 4 -d "'")
  trace "-> Add repository[$repo]" 
  trace "  with key[$key]"
  sudo apt-key adv --recv-keys --keyserver $key
  sudo add-apt-repository "$repo"
  update
}

trt_deb() {
  packet=$2
  version=$3
  install_deb $packet $version
}

install_buntufile() {
  while read line; do
    install_line $line
  done < <(grep -v '^#' $buntufile)
}

init
update
upgrade
install_buntufile
sortie 0
