#!/bin/bash
# Palette installer votre distrib xBuntu grâce à un Buntufile ! 

#Chargement des bibliothèques
charge_libs()
{
  listeLibs="log std"
  for lib in $listeLibs; do
    . ${SFLIB}/${lib}.lib || erreur "Chargmenent de la bibliothèque [$lib] : impossible "
    sflib_log_debug "Chargmenent de la bibliothèque [$lib] : OK"
    sflib_${lib}_init || "Initialisation de la bibliothèque [$lib] : impossible "
    sflib_log_debug "Initialisation de la bibliothèque [$lib] : OK"
  done
}

init() {
  export SFLIB=/home/christophe/dev/app/shellfactory/lib
  charge_libs
  buntufile=Buntufile
  sflib_std_fic_test $buntufile
}

sortie() {
  rc=$1
  [ $SEVERITE -ne 0 ] && rc=$SEVERITE
  [ $rc -eq 0 ] && trace "Palette install completed." || erreur "Palette install error [$rc]"
  exit $rc
}

test_os() {
  trace "Test OS version"
  grep "$os_version" /etc/issue >/dev/null|| (trace "OS not $os_version" && sortie 1)
  trace " --> Os OK"
}

upgrade() {
  trace "Upgrade packages"
  sudo dpkg --configure -a >/dev/null
  sudo apt-get update -y >/dev/null
  sudo apt-get upgrade -y  >/dev/null
}

install_deb() {
  trace "  --> Install packet apt $packet"
  sudo apt-get install -y $packet >/dev/null
  sflib_std_test_returncode "    Installation du packet impossible"
}

install_line() {
  mot_clef=$(echo $line|cut -f 1 -d ' ')
  case $mot_clef in
    source|deb) 
    trt_$mot_clef;;
    '');;
    *) warning "Mot clef [$mot_clef] inconnu !"
  esac
}

trt_source() {
  trace "Traitement source [$line]"
}

trt_deb() {
  trace "Traitement deb [$line]"
  packet=$(echo $line|cut -f 2 -d ' ')
  install_deb $packet
}

install_buntufile() {
  while read line; do
    install_line $line
  done < <(grep -v '^#' $buntufile)
}

init
upgrade
install_buntufile
sortie 0
